- project:
    templates:
      - openstack-python3-charm-jobs
      - openstack-cover-jobs
      - prometheus-alert-rules-test
    vars:
      charm_build_name: openstack-hypervisor
      juju_channel: 3.1/stable
      juju_classic_mode: false
      microk8s_channel: 1.28-strict/stable
      microk8s_classic_mode: false
      prometheus_alerts_test_rules_dir: tests/unit/test_alert_rules
